Use zoneinfo to get stlist

diff --git a/stbackup b/stbackup
--- a/stbackup
+++ b/stbackup
@@ -1,26 +1,23 @@
 #!/usr/bin/env bash
 timestamp=$(date +%Y%m%d%H%M)
 
-# Esto es magia arcana con arrays de bash
-hosts=($(/guifibages/sbin/list-st))
-limit=$(( ${#hosts[*]}-2 ))
-
+zona=${1:-bages}
 function cagonla {
   echo $* >&2
   exit -1
 }
 
-for i in `seq 0 2 $limit`
+for i in `./zoneinfo.py -f csv -s $zona`
 do
-  hostname=${hosts[$i]}
-  ip=${hosts[$(($i+1))]}
+  hostname=$(echo $i | awk -F, '{print $2}')
+  ip=$(echo $i | awk -F, '{print $3}')
   backupdir=/guifibages/backup/st/$hostname
   backupfile=$backupdir/$hostname-$timestamp.export
   [ -d backupdir ] || mkdir -p $backupdir || cagonla No es pot crear el directori $backupdir
 
-  echo "$timestamp Fent backup de $hostname $ip"
+  echo "$timestamp Fent backup de $hostname $ip $lastfile $backupfile"
   lastfile=$backupdir/$(ls -t $backupdir| head -1)
-  ssh -o StrictHostKeyChecking=no guest@$ip /export compact > $backupfile || echo "Error al fer export de $hostname ($ip)" >&2
+  ssh -o StrictHostKeyChecking=no -o PasswordAuthentication=no guest@$ip /export compact > $backupfile || echo "Error al fer export de $hostname ($ip)" >&2
 
   # Si son iguals, crear un enlla√ fort. Ignorar 27 primers bytes (data de backup)
 
